<?php

/**
 * ProcessWire Configuration File
 *
 * Site-specific configuration for ProcessWire.
 * This config.php file was generated by the ProcessExportProfile module. 
 *
 * Please see the file /wire/config.php which contains all configuration options you may
 * specify here. Simply copy any of the configuration options from that file and paste
 * them into this file in order to modify them.
 *
 * ProcessWire 2.x
 * Copyright (C) 2014 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://processwire.com
 *
 */

if(!defined("PROCESSWIRE")) die();

/*** SITE CONFIG *************************************************************************/

/**
 * Enable debug mode?
 *
 * Debug mode causes additional info to appear for use during dev and debugging.
 * This is almost always recommended for sites in development. However, you should
 * always have this disabled for live/production sites.
 *
 * @var bool
 *
 */
$config->debug = (getenv('PW_ENV') == 'production') ? false : true;

// So PW doesn't kill the session on reverse proxied clustered installations
$config->sessionFingerprint = false;

// So RDS can take backups
$config->dbEngine = 'InnoDB';

ini_set('session.save_handler', getenv('PW_CACHE_DRIVER'));
ini_set('session.save_path',    getenv('PW_CACHE_HOST'));

/*** INSTALLER CONFIG ********************************************************************/

/**
 * Installer: Database Configuration
 *
 */
$config->dbHost = getenv('PW_DB_HOST');
$config->dbName = getenv('PW_DB_NAME');
$config->dbUser = getenv('PW_DB_USER');
$config->dbPass = getenv('PW_DB_PASS');
$config->dbPort = getenv('PW_DB_PORT');

/**
 * Installer: User Authentication Salt
 *
 * Must be retained if you migrate your site from one server to another
 *
 */
$config->userAuthSalt = getenv('PW_SALT');

/**
 * Installer: File Permission Configuration
 *
 */
$config->chmodDir = '0755'; // permission for directories created by ProcessWire
$config->chmodFile = '0644'; // permission for files created by ProcessWire

/**
 * Installer: Time zone setting
 *
 */
$config->timezone = 'Europe/Helsinki';


/**
 * Installer: HTTP Hosts Whitelist
 *
 */
$config->httpHosts = array(getenv('PW_URL'));

